### ISSUE TITLE
enable RSS

### ISSUE THREAD

**Issue by tpepper** [lwkd/lwkd.github.io#1]
Is it possible to enable an RSS feed for the http://lwkd.info/ site?

**Comment by jberkus** [comment]
I'd have to hand-code it, unless you know a widget somewhere that does it.

**Comment by jberkus** [comment]
My first thought is to write a script that generates RSS feeds from the files.

**Comment by jberkus** [comment]
So I've looked into using Hugo.io for this.  However, the instructions for publishing Github Pages from hugo.io are rather complicated, enough that hand-writing the XML seems like an easier course.  Anyone set up that toolchain before?

**Comment by coderanger** [comment]
You can use the jekyll-feed plugin on github pages but it would require reworking things a little so that the posts are recognized as posts in the jekyll format. On the plus side, doing that would also allow automating the list of links on the index page. Is that okay? I've been poking at the code and can put up a PR.

**Comment by jberkus** [comment]
Wow, thanks!  I'm at the Helm Summit right now, but I should be able to review this and try it out on Friday.
